TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.db_process,DBProcessTrain
  num_workers: 2
  img_set_dir: ../../input/icdar2015/
  label_file_path: ../../input/icdar2015/train_icdar2015_label.txt

EvalReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  img_set_dir: ../../input/icdar2015/
  label_file_path: ../../input/icdar2015/test_icdar2015_label.txt
  test_image_shape: [736, 1280]
  
TestReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  img_set_dir: ../../input/icdar2015/
  label_file_path: ../../input/icdar2015/test_icdar2015_label.txt
  do_eval: True
